---
- name: Install Node Exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present
    update_cache: true

- name: Enable Node Exporter service
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true

- name: Restrict Node Exporter to monitoring network
  community.general.ufw:
    rule: allow
    port: "{{ node_exporter_port }}"
    proto: tcp
    from_ip: "{{ node_exporter_monitoring_cidr }}"
