---
- name: Create exporter network
  community.docker.docker_network:
    name: internal
    state: present

- name: Run Nginx Prometheus Exporter
  community.docker.docker_container:
    name: nginx-prometheus-exporter
    image: "{{ nginx_exporter_image }}"
    state: started
    restart_policy: unless-stopped
    command:
      - "-nginx.scrape-uri={{ nginx_exporter_scrape_uri }}"
    published_ports:
      - "{{ nginx_exporter_port }}:9113"
    networks:
      - name: internal
