apiVersion: 1

contactPoints:
  - orgId: 1
    name: bulletin-board-webhook
    receivers:
      - uid: bulletin-board-webhook
        type: webhook
        settings:
          url: $__env{ALERT_WEBHOOK_URL}
          httpMethod: POST
